### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by pramodshinde**
- Fixed typo in README
- Added completed? method example use to README.

### CODE REVIEW

**Comment by RobertoSchneiders** [comment]
:+1:

**Comment by RobertoSchneiders** [comment]
Thanks! I will wait for the https://github.com/verifalia/verifalia-ruby-sdk/pull/10 before merge it.

**Comment by pramodshinde** [comment]
@RobertoSchneiders - Do you think this is depended on #10 ?

**Comment by RobertoSchneiders** [comment]
My mistake @pramodshinde.

**Pull request merged**
